### ISSUE TITLE
出现报错：AssertionError: Torch not compiled with CUDA enabled[QA] 

### ISSUE THREAD

**Issue by kakabai** [InternLM/InternLM#430]
### Describe the question.

我使用的20B-4bit的模型，显卡是2080ti魔改22g.CUDA版本比官方要求的11.7高一个版本，是11。8运行时报错，AssertionError: Torch not compiled with CUDA enabled。好像是不能启动。请问怎么办？torch版本是2.0.1。

**Comment by kakabai** [comment]
补充，我测试torch+cuda11.8是好的

**Comment by ZwwWayne** [comment]
Seems the issue has been solved by torch + cuda 11.8. Thus the issue is closed.
