### ISSUE TITLE
[Bug] failing everytime and getting CUDA out of memory

### ISSUE THREAD

**Issue by HAIXteam** [InternLM/InternLM#724]
### Describe the bug

failing everytime and getting CUDA out of memory . We using GPU of nvidia A100 GPU (with 24 vcpu and 220 GIB memory)

### Environment

failing everytime and getting CUDA out of memory . We using GPU of nvidia A100 GPU (with 24 vcpu and 220 GIB memory)

### Other information

failing everytime and getting CUDA out of memory . We using GPU of nvidia A100 GPU (with 24 vcpu and 220 GIB memory)

**Comment by StupidBuluchacha** [comment]
same issue here!

**Comment by del-zhenwu** [comment]
remove stale

**Comment by Healthyyue** [comment]
same issue here! I cloned internlm2-chat-1.8b several days ago, but it turns out that I got OOM. I used 1650 super and 16GB RAM. No sure what issue happened.

**Comment by ZwwWayne** [comment]
For InternLM2-20B, it might be the issue with TP, you may try to use TP=2. For InternLM2-1.8B, this is a weird issue, could you provide more information about the environment, such as the version of pytorch and transformers?
