### ISSUE TITLE
[Bug] CUDA out of memory on 8 GTX4090

### ISSUE THREAD

**Issue by yibomiao** [InternLM/InternLM#79]
### Describe the bug

I found that a single RTX4090 (24G) can not load InternLM-Chat-7B model. But when I use `device_map="auto"` , an exception occurs:

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 0; 23.65 GiB total capacity; 22.99 GiB already allocated; 154.06 MiB free; 22.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
 I don't know why it didn't evenly utilize multiple GPUs. Therefore, the first GPU  is out of Memory.

![intern](https://github.com/InternLM/InternLM/assets/45325713/1ef360cb-d99c-4865-889a-ccecc26d568a)

Here is the code I use:
```
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("internlm/internlm-chat-7b", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("internlm/internlm-chat-7b", device_map="auto", trust_remote_code=True).cuda()
model = model.eval()

response, history = model.chat(tokenizer, "hello", history=[])
print(response)
```
The error happens when executing 
 `model = AutoModelForCausalLM.from_pretrained("internlm/internlm-chat-7b", device_map="auto", trust_remote_code=True).cuda()`

What's the reason for this error?

### Environment

```
python 3.8
cuda 11.7
```

**Comment by wangruohui** [comment]
Hi,

You can try fp16
https://github.com/InternLM/InternLM/pull/80

**Comment by yuxuan2015** [comment]
@yibomiao 改成model = AutoModelForCausalLM.from_pretrained("internlm/internlm-chat-7b", device_map="auto", trust_remote_code=True).half().cuda()，就不会显存溢出了，感觉是 bfloat16 的问题

**Comment by yibomiao** [comment]
> Hi,
> 
> You can try using FP16 like #80. It should use around 17GB memory for model.
> 
> If you want to use naive pipeline parallel (with huggingface/accelerate), you may also try `device_map="balanced"` to balance memory on all devices. Using single GPU should be faster if there are enough GPU memory.

Thanks, using FP16 works for me.
